/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'abaccega' at '7/9/18 1:36 PM' with Gradle 2.10
 *
 * @author abaccega, @date 7/9/18 1:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
